<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3b954bf7-cc8c-48df-9b96-ec98f47ce0f9</testSuiteGuid>
   <testCaseLink>
      <guid>925be5d4-28a5-41bc-8143-0cfc02215aa0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tugas Week 1/Login Berhasil</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c75c3ba9-ccaa-4968-ae05-dc623bac68e1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c75c3ba9-ccaa-4968-ae05-dc623bac68e1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>960ee992-ceed-4795-b460-b4d1c36726b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c75c3ba9-ccaa-4968-ae05-dc623bac68e1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>7996b6cb-f104-4458-96be-896e3c169a26</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
