<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>continue</description>
   <name>buttton_continue</name>
   <tag></tag>
   <elementGuidId>7f96ed69-e58e-46f8-9975-8915e61d3296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;continue&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
