<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Login</description>
   <name>button_login</name>
   <tag></tag>
   <elementGuidId>dee329dd-0d86-4736-bdc1-e358653dfa93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;login-button&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
