<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Password</description>
   <name>textbox_password</name>
   <tag></tag>
   <elementGuidId>e25bcf65-d0c3-4e6a-9bec-930fb8825b3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
